package com.mageshowdown.gameclient;

import com.esotericsoftware.kryonet.Connection;
import com.esotericsoftware.kryonet.Listener;
import com.mageshowdown.gamelogic.GameScreen;
import com.mageshowdown.gamelogic.GameWorld;
import com.mageshowdown.packets.Network;

public class ClientListener extends Listener {

    private GameClient myClient = GameClient.getInstance();

    private GameScreen gameScreen;

    public ClientListener(GameScreen gameScreen) {
        this.gameScreen = gameScreen;
    }

    @Override
    public void connected(Connection connection) {
    }

    @Override
    public void received(Connection connection, Object object) {
        handleLoginServerRequest(connection, object);
        handleNewPlayerSpawned(connection, object);
        handleUpdateCharacterStates(connection, object);
        handleShootProjectile(connection, object);
        handleProjectileCollided(connection, object);
        handlePlayerDisconnected(connection, object);
        handleCurrentMap(connection, object);
        handlePlayerDead(connection, object);
        handleSwitchWeapons(connection, object);
    }

    private void handleLoginServerRequest(Connection connection, Object object) {
        if (object instanceof Network.LoginRequest) {
            Network.LoginRequest packet = ((Network.LoginRequest) object);
            System.out.println("received login request!");
            packet.user = myClient.getUserName();
            System.out.println(packet.user);
            myClient.sendTCP(packet);
        }
    }

    private void handleUpdateCharacterStates(Connection connection, Object object) {
        if (object instanceof Network.CharacterStates) {
            Network.CharacterStates packet = ((Network.CharacterStates) object);
            /*
             * In order to make sure the box2d world doesnt get locked when we synchronize the
             * velocity and position of a body, we have to queue these assignments
             * and do them after the world has stepped;
             */
            for (Network.OneCharacterState x : packet.playerStates) {
                ClientPlayerCharacter pc;
                //if the character is mine i update my position
                if (x.id == connection.getID()) {
                    pc = GameScreen.getGameStage().getPlayerCharacter();
                } else {
                    pc = GameScreen.getGameStage().getOtherPlayers().get(x.id);
                }

                pc.setQueuedPos(x.pos);
                pc.setQueuedVel(x.linVel);
                pc.setHealth(x.health);
                pc.setEnergyShield(x.energyShield);
                pc.setScore(x.score);
                pc.setDmgImmune(x.dmgImmune);
                pc.setFrozen(x.frozen);
                pc.setKills(x.kills);
            }
        }
    }

    private void handleNewPlayerSpawned(Connection connection, Object object) {
        if (object instanceof Network.NewPlayerSpawned) {
            Network.NewPlayerSpawned packet = (Network.NewPlayerSpawned) object;
            System.out.println(packet.id);
            //the position generated by the spawn function is for box2d world coordinates so it needs to be converted
            packet.pos = GameWorld.convertWorldToPixels(packet.pos);
            ClientRound.getInstance().setTimePassed(packet.roundTimePassed);
            if (connection.getID() == packet.id && GameScreen.getGameStage().getPlayerCharacter() == null) {
                GameScreen.getGameStage().spawnMyPlayerCharacter(packet.pos, packet.userName);
                GameScreen.getGameStage().getPlayerCharacter().setMyPlayer(true);
                GameScreen.getGameStage().getPlayerCharacter().setID(packet.id);
            } else {

                GameScreen.getGameStage().spawnOtherPlayer(packet.id, packet.pos, packet.userName);
            }
        }
    }

    private void handleShootProjectile(Connection connection, Object object) {
        if (object instanceof Network.ShootProjectile) {
            Network.ShootProjectile packet = (Network.ShootProjectile) object;

            GameScreen.getGameStage().getOtherPlayers().get(packet.id).getCurrWeapon().shoot(packet.dir, packet.rot, packet.id);
        }
    }

    private void handleProjectileCollided(Connection connection, Object object) {
        if (object instanceof Network.ProjectileCollided) {
            Network.ProjectileCollided packet = (Network.ProjectileCollided) object;

            //if the bullet is the client's player's
            if (packet.ownerId == connection.getID()) {
                GameScreen.getGameStage().getPlayerCharacter().getCurrWeapon().projectileHasCollided(packet.projId);
            }
            //if the bullet is some other client's player's
            else {
                GameScreen.getGameStage().getOtherPlayers().get(packet.ownerId).getCurrWeapon().projectileHasCollided(packet.projId);
            }
        }
    }

    private void handlePlayerDisconnected(Connection connection, Object object) {
        if (object instanceof Network.PlayerDisconnected) {
            Network.PlayerDisconnected packet = (Network.PlayerDisconnected) object;

            GameScreen.getGameStage().removePlayerCharacter(packet.id);
        }
    }

    private void handleCurrentMap(Connection connection, Object object) {
        if (object instanceof Network.CurrentMap) {
            Network.CurrentMap packet = (Network.CurrentMap) object;

            GameScreen.getGameStage().getGameLevel().setMap(packet.nr);
            GameScreen.getGameStage().getGameLevel().changeLevel();
        }
    }

    private void handlePlayerDead(Connection connection, Object object) {
        if (object instanceof Network.PlayerDead) {
            Network.PlayerDead packet = (Network.PlayerDead) object;

            if (packet.id == GameClient.getInstance().getID()) {
                System.out.println("you died you suck");
            } else {
                System.out.println(packet.id + " died he sucks");
            }
        }
    }

    private void handleSwitchWeapons(Connection connection, Object object) {
        if (object instanceof Network.SwitchWeapons) {
            Network.SwitchWeapons packet = (Network.SwitchWeapons) object;

            GameScreen.getGameStage().getOtherPlayers().get(packet.id).switchMyWeapons();
        }
    }
}

